### ISSUE TITLE
Stackoverflowerror with a tar containing many files

### ISSUE THREAD

**Issue by mikmakmuk** [JDatta/TarFileSystem#6] opened 2017-04-14 19:03 UTC
I've a tar with ~160000 files which produces a Stackoverflowerror (see below). Not sure where the problem is. Running the job on 160000 files (not tarred) works fine.

`Exception in thread "main" java.lang.StackOverflowError
        at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:721)
        at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:355)
        at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:656)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:882)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:934)
        at java.io.DataInputStream.read(DataInputStream.java:100)
        at org.apache.hadoop.fs.tar.TarFileSystem.readHeaderBuffer(TarFileSystem.java:191)
        at org.apache.hadoop.fs.tar.TarFileSystem.readHeaderEntry(TarFileSystem.java:179)
        at org.apache.hadoop.fs.tar.TarFileSystem.getFileStatus(TarFileSystem.java:288)
        at org.apache.hadoop.fs.tar.TarFileSystem.listStatus(TarFileSystem.java:208)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1517)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1557)
        at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1714)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1713)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1696)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:343)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
`

**Comment by JDatta** [comment] 2017-04-16 03:41
Will look into it

**Comment by JDatta** [comment] 2017-04-16 03:42
Which version of Hadoop are you using?

**Comment by mikmakmuk** [comment] 2017-04-16 06:58
I'm using 2.7.3. If you need the data on which I receive the error, I can provide it as it is open-source data. Thanks for looking into this!

**Comment by JDatta** [comment] 2017-04-17 12:09
What is the depth of dir hierarchy in the dataset? I am asking this because in the trace, the only recursive call is at `addInputPathRecursively(FileInputFormat.java:348)`.

**Comment by mikmakmuk** [comment] 2017-04-17 12:41
This counts the "/" in the paths:
$ find . -type f | awk -F\/ '{print NF-1}' | sort -nr | head -1
21

So 21 seems to be the deepest hierarchy in the dataset.
Could you reproduce the exception?

**Comment by JDatta** [comment] 2017-04-18 06:34
Can you please attach the full log file for me to debug? 

I haven't yet reproduced the issue. I need to first prepare the dataset.

**Comment by mikmakmuk** [comment] 2017-04-18 07:11
Yes (see below). You can also get the dataset and the map/reduce job (standard word count):
[Dataset](https://data.lmsteiner.com/systems.tar.bz2)
[Jar](https://data.lmsteiner.com/wc.jar)

`hadoop jar wc.jar tar://Qualitas/systems.tar /user/mun/Qualitas/output
17/04/18 09:02:09 INFO tar.TarFileSystem: *** Using Tar file system ***
17/04/18 09:02:14 INFO client.RMProxy: Connecting to ResourceManager at localhost/127.0.0.1:8032
17/04/18 09:02:14 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
17/04/18 09:02:37 INFO mapreduce.JobSubmitter: Cleaning up the staging area /tmp/hadoop-yarn/staging/mun/.staging/job_1492498902043_0001
Exception in thread "main" java.lang.StackOverflowError
        at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:721)
        at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:355)
        at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:656)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:882)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:934)
        at java.io.DataInputStream.read(DataInputStream.java:100)
        at org.apache.hadoop.fs.tar.TarFileSystem.readHeaderBuffer(TarFileSystem.java:191)
        at org.apache.hadoop.fs.tar.TarFileSystem.readHeaderEntry(TarFileSystem.java:179)
        at org.apache.hadoop.fs.tar.TarFileSystem.getFileStatus(TarFileSystem.java:288)
        at org.apache.hadoop.fs.tar.TarFileSystem.listStatus(TarFileSystem.java:208)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1517)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1557)
        at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1714)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1713)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1696)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:343)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)                                                                                                                                                                                                                                   
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:348)
[...]`

**Comment by JDatta** [comment] 2017-04-19 05:57
With your dataset, I could reproduced the issue in unit test environment. Will look into it.

**Comment by JDatta** [comment] 2017-04-21 10:17
Found the issue in code. In short, the issue is, the code does not support directories within a tar yet. Will work on a possible fix...

**Comment by JDatta** [comment] 2017-04-22 04:59
Supporting hierarchical directory structure in TarFileSystem is non-trivial. Will create an issue for that and track separately.

For now, there was a bug in the code which excluded directory entries from TarFilesystem index. Fixed that. With this the stack-overflow error should be solved.

Code change added in PR #8 and is available in master branch.

**Comment by JDatta** [comment] 2017-04-23 04:17
Resolving this one. Please reopen if the bug is seen again.

**Closed by JDatta** 2017-04-23 04:17 UTC
Labels: bug
